version: '3.8'

services:
  db:
    image: postgres:12
    ports:
      - "5433:5432"

    environment:
      - POSTGRES_PASSWORD= password
      - POSTGRES_USER= postgres-user
      - POSTGRES_DB= project_48_test

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"  # Map container port 80 to host port 8080
    volumes:
      - frontend:/app/build

#  nginx:
#    build:
#      context: ./nginx
#    volumes:
#      - static:/static
#      - frontend:/var/www/frontend
#    ports:
#      - "80:80"
#    depends_on:
#      - backend
#      - frontend

volumes:
  static:
  frontend:
